import {
  AE,
  AT,
  AU,
  BE,
  BG,
  BR,
  CA,
  CH,
  CY,
  CZ,
  DE,
  DK,
  EE,
  ES,
  FI,
  FR,
  GB,
  GI,
  GR,
  HK,
  HR,
  HU,
  IE,
  IT,
  JP,
  LI,
  LT,
  LU,
  LV,
  MT,
  MX,
  MY,
  NL,
  NO,
  NZ,
  PL,
  PT,
  RO,
  SE,
  SG,
  SI,
  SK,
  TH,
  US,
} from "country-flag-icons/react/3x2";

// make sure that the names matches what stripe uses internally
// For card type, use the brand name from stripe
export const PAYMENT_METHOD_NAMES_AND_ICONS = [
  { name: "mastercard", icon: "/icon/payment-methods/mastercard.svg" },
  { name: "visa", icon: "/icon/payment-methods/visa.svg" },
  { name: "amex", icon: "/icon/payment-methods/amex.svg" },
  { name: "discover", icon: "/icon/payment-methods/discover.svg" },
  { name: "jcb", icon: "/icon/payment-methods/jcb.svg" },
  { name: "diners", icon: "/icon/payment-methods/diners.svg" },
  { name: "unionpay", icon: "/icon/payment-methods/unionpay.svg" },
  { name: "amazon_pay", icon: "/icon/payment-methods/amazonpay.svg" },
  { name: "cashapp", icon: "/icon/payment-methods/cashapp.svg" },
] as const;

export const COUNTRIES_SUPPORTED_BY_STRIPE = [
  { name: "United States", Flag: US },
  { name: "Canada", Flag: CA },
  { name: "United Kingdom", Flag: GB },
  { name: "Australia", Flag: AU },
  { name: "Austria", Flag: AT },
  { name: "Belgium", Flag: BE },
  { name: "Brazil", Flag: BR },
  { name: "Bulgaria", Flag: BG },
  { name: "Croatia", Flag: HR },
  { name: "Cyprus", Flag: CY },
  { name: "Czech Republic", Flag: CZ },
  { name: "Denmark", Flag: DK },
  { name: "Estonia", Flag: EE },
  { name: "Finland", Flag: FI },
  { name: "France", Flag: FR },
  { name: "Germany", Flag: DE },
  { name: "Gibraltar", Flag: GI },
  { name: "Greece", Flag: GR },
  { name: "Hong Kong", Flag: HK },
  { name: "Hungary", Flag: HU },
  { name: "Ireland", Flag: IE },
  { name: "Italy", Flag: IT },
  { name: "Japan", Flag: JP },
  { name: "Latvia", Flag: LV },
  { name: "Liechtenstein", Flag: LI },
  { name: "Lithuania", Flag: LT },
  { name: "Luxemburg", Flag: LU },
  { name: "Malaysia", Flag: MY },
  { name: "Malta", Flag: MT },
  { name: "Mexico", Flag: MX },
  { name: "Netherlands", Flag: NL },
  { name: "New Zealand", Flag: NZ },
  { name: "Norway", Flag: NO },
  { name: "Poland", Flag: PL },
  { name: "Portugal", Flag: PT },
  { name: "Romania", Flag: RO },
  { name: "Singapore", Flag: SG },
  { name: "Slovakia", Flag: SK },
  { name: "Slovenia", Flag: SI },
  { name: "Spain", Flag: ES },
  { name: "Sweden", Flag: SE },
  { name: "Switzerland", Flag: CH },
  { name: "Thailand", Flag: TH },
  { name: "United Arab Emirates", Flag: AE },
];
